import { Montserrat as FontSans } from "next/font/google";
import "./globals.css";

import { cn } from "../lib/utils";
import { MyThemeProvider } from "@/components/my-theme-provider";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen font-sans bg-muted antialiased",
          fontSans.variable
        )}
      >
        <MyThemeProvider
          themes={["light", "dark", "barbie"]}
          defaultTheme="system"
        >
          <div className="container bg-background h-[100dvh]">{children}</div>
        </MyThemeProvider>
      </body>
    </html>
  );
}
